### ISSUE TITLE
[Bug]: AttributeError: EndShipper object has no attribute _unsaved_values

### ISSUE THREAD

**Issue by tomaszpiotro** [EasyPost/easypost-python#298]
### Software Version

8.1.1

### Language Version

3.8

### Operating System

Ubuntu

### What happened?

We cannot set properties of EasyPostObjects
code from https://github.com/EasyPost/easypost-python/blob/12fb76765c67c35e07f2fba9b106c0585614b151/easypost/easypost_object.py#L107-L120

Problem is  self._unsaved_values is not initiated anywhere.
Is _unsaved_values even used anywhere? 

### What was expected?

setting an attribute on any EasyPostObject should be possible

### Sample Code

```
client.customs_item.create(description="asd", quantity=1, value=1, weight=1)
customs.weight = 2

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/easypost/easypost_object.py", line 112, in __setattr__
    self._unsaved_values.add(k)
  File "/usr/local/lib/python3.8/site-packages/easypost/easypost_object.py", line 127, in __getattr__
    raise AttributeError(NO_ATTRIBUTE_ERROR.format(type(self).__name__, k))
AttributeError: CustomsItem object has no attribute _unsaved_values
```
Where client is EasyPostClient
_No response_

**Comment by Justintime50** [comment]
Hey @tomaszpiotro, thanks for writing in. Can you provide a real code snippet of what you are trying to accomplish here so we can attempt to recreate the problem?

**Comment by tomaszpiotro** [comment]
> Hey @tomaszpiotro, thanks for writing in. Can you provide a real code snippet of what you are trying to accomplish here so we can attempt to recreate the problem?

```
client.customs_item.create(description="asd", quantity=1, value=1, weight=1)
customs.weight = 2

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/easypost/easypost_object.py", line 112, in __setattr__
    self._unsaved_values.add(k)
  File "/usr/local/lib/python3.8/site-packages/easypost/easypost_object.py", line 127, in __getattr__
    raise AttributeError(NO_ATTRIBUTE_ERROR.format(type(self).__name__, k))
AttributeError: CustomsItem object has no attribute _unsaved_values
```
Just setting any attribute on any EasyPostObject throws this error. I think it was possible in a previous release of this lib

**Comment by Justintime50** [comment]
> I think it was possible in a previous release of this lib

Correct, in previous major releases, this was possible; however, to avoid mixed context of local objects vs objects received from the API, we migrated all of our client libraries to this new approach where objects are immutable from the API. You first create a client, then call a service on that client (eg: shipments, parcels, addresses, etc), then call an action on that service (create, retrieve, etc). This ensures that objects going to and coming back from the API are consistent. If you want to alter the properties of an object, you'll need to do that when calling the action on a service (in this example, at the time of creation).

Does this make sense? Can you help me understand the previous use case for needing to alter a property independently of sending that data to the API?

**Comment by Justintime50** [comment]
Hey @tomaszpiotro, I'm going to close this as I haven't heard back from you in awhile, but feel free to reopen with additional comments if needed! Would love to hear about your use case to see if there isn't something we can do.

**Comment by tomaszpiotro** [comment]
Yea @Justintime50 immutability makes sense here. I'm not exactly sure what was the use case in the project i worked on. I just had to upgrade it from older version and it for some reason was mutating an object. 
TBH I would throw here some more verbose exception. So that way it would be clear for developer that those objects are supposed to be immutable

**Comment by DanielSwain** [comment]
Our system creates a `Shipment` object at the time someone makes a purchase.  In our shipping screen, if it is an international shipment, then we create the customs information and add it to the shipment object.  The `CustomsInfo`/`CustomsItem` object combination is created successfully:
`customs_info = easypost_client.customs_info.create(**customs_info_data)`
But then the next lines
```
shipment = easypost_client.shipment.retrieve(easypost_shipment_id)
shipment.customs_info = customs_info
shipment.save()
```
yield the same error referenced in this issue:
`AttributeError: Shipment object has no attribute _unsaved_values`

How can this problem be fixed?  We HAVE to be able to add customs information to a shipment.  Surely it is common practice to create Customs information at the time of preparing a shipment and purchasing the label rather than at the time of purchase.  When using EasyPost on WooCommerce, I know that customs information can be added after the fact, so it seems like it's just a problem with this library.  Do the architectural changes introduced in V8 of this library preclude adding customs information to an existing Shipment?  If so, this is very concerning.

**Comment by LoganSimonsen** [comment]
After creation, EasyPost shipment objects are immutable. So for API users, I would recommend just creating a second shipment if you want to make any changes further along your workflow. You can still manage a 2-call workflow. it would look like:

1. [create a shipment](https://www.easypost.com/docs/api#create-a-shipment) - using whatever filler customs_info you want you can retrieve rates for the shipment. The entire shipment object will be returned in the response, including id. I would save this object to a variable and then delete the id and customs_info and use the remaining object to build a new shipment with a...
2. [one-call buy](https://www.easypost.com/docs/api#buy-a-shipment-without-rating-one-call-buy) - With a one-call buy, we are creating a new shipment object within EasyPost and specifying a new customs_info and carrier and service that we want to buy (chosen from rates returned in step 1).

**Comment by DanielSwain** [comment]
@LoganSimonsen Upon further searching I found [this issue](https://github.com/EasyPost/easypost-php/issues/62) in the EasyPost PHP library where someone was trying to add CustomsInfo to a Shipment and a reply was given that [Shipment objects are immutable](https://github.com/EasyPost/easypost-php/issues/62#issuecomment-429932210).  The word "immutable" does not appear **ANYWHERE** on the [EasyPost API docs page](https://www.easypost.com/docs/api/).  Also, the [created_at/updated_at](https://www.easypost.com/docs/api/python#customs-infos:~:text=created_at/updated_at%3A) explanation at the top of the docs under [EasyPost objects](https://www.easypost.com/docs/api/python#objects) makes it sound like most objects **CAN** be mutated (because of the existence of the `updated_at` attribute).  Further, the [upgrade instructions for V8 of this library](https://github.com/EasyPost/easypost-python/blob/v8.0.0/UPGRADE_GUIDE.md#80-easypostclient) discuss the change from `.save()` to `.update()`, but again, nowhere is it stated that Shipment objects are immutable and so do not even have an `.update()` attribute.  Based upon the V8 docs (and wishful thinking, despite your statement that Shipment objects are immutable), I tried:

```
customs_info = easypost_client.customs_info.create(**customs_info_data)
easypost_client.shipment.update(shipment.id, customs_info = customs_info)
```
So of course I then got the error:  AttributeError: 'ShipmentService' object has no attribute 'update'

I then looked through a number of the files in the `services` folder in the repo, and the only service that I saw with an `update` attribute/function was `user_service.py`.  I think the API docs are severely lacking in explaining all of this.  It seems that at least the following four things would be very helpful:

1. A statement at the top of the API docs in bold type that most objects are **immutable** and then provide a list of on-page links to the objects which are mutable (I can find only four when I do an on-page search for both `PATCH` and `".update("`. 
2. Place a note in the explanation of [created_at/updated_at](https://www.easypost.com/docs/api/python#customs-infos:~:text=created_at/updated_at%3A) that most objects are immutable and so the `updated_at` value would nearly always equal the `created_at` value.
3. Under the CustomsInfo section of the API docs, provide the example you gave above about how to add Customs information after a Shipment has been created.
4. Since V8 of this library was such a large change, in the [section of those docs](https://github.com/EasyPost/easypost-python/blob/v8.0.0/UPGRADE_GUIDE.md#80-easypostclient) that mentions the change from `.save()` to `.update()`, add a statement that most objects are immutable and that only certain objects have an `.update()` function.  Then provide a link to the the part of the API docs described in number 1 above.

**Comment by nwithan8** [comment]
@DanielSwain thank you for the suggestions for improvements to our docs. We have noted them internally and will work to incorporate them to clarify the immutability of Shipments et al.

We also apologize for the confusion regarding the workflow to add customs information to a shipment. It would appear the v8 upgrade guide contained incorrect information that we are working to rectify.

**Comment by LoganSimonsen** [comment]
@DanielSwain you make good points. When I said previously that shipment objects were immutable I should have clarified that they are not able to be updated by the API user after creation. EasyPost will update shipment objects during the course of a shipment's lifecycle and that is when I would expect the `created_at` date to be updated. All such activities happen on the EasyPost backend. EasyPost will update `shipment.status`, `shipment.fees` and number of different values within the `shipment.tracker` object etc.
