### ISSUE TITLE
batch_api_obj.label() returning 'AttributeError'

### ISSUE THREAD

**Issue by humbertomn** [EasyPost/easypost-python#63]
Call:

batch_api_obj = self.easypost.Batch.retrieve(shipping_api_batch_uuid)
batch_api_obj.label(file_format='pdf')

Returning "AttributeError: 'NoneType' object has no attribute 'items'"

_Traceback (most recent call last):
  File ".../shipping_processor.py", line 504, in batch_generate_label
    batch_api_obj.label(file_format='pdf')
  File "/thewinegallery/src/thewinegalleryvenv/lib/python3.4/site-packages/easypost/__init__.py", line 810, in label
    self.refresh_from(response, api_key)
  File "/thewinegallery/src/thewinegalleryvenv/lib/python3.4/site-packages/easypost/__init__.py", line 452, in refresh_from
    for k, v in sorted(six.iteritems(values)):
  File "/thewinegallery/src/thewinegalleryvenv/lib/python3.4/site-packages/six.py", line 581, in iteritems
    return iter(d.items(**kw))
AttributeError: 'NoneType' object has no attribute 'items'_

**Comment by geddes** [comment]
Hi Humberto - you need to set the label type option on a per shipment basis, not as part of the order object.

**Comment by humbertomn** [comment]
Hi @geddes. What do you mean? This call has been working fine since we launched and here it is in the docs: https://www.easypost.com/docs/api/python.html#batch-labels

The error is happening only a few times (say 5 times a week) when we process the label request after receiving an update from an EasyPost webhook.

**Comment by geddes** [comment]
From humbertomn - 

I've been getting this several times a day.

Our webhook receives data from EasyPost and makes this call (Python):

batch_api_obj = self.easypost.Batch.retrieve(shipping_api_batch_uuid) 
batch_api_obj.label(file_format='pdf')

And it fails like:

Task xxxx.xxxxx.tasks.process_webhook[97e195e0-70df-4413-a1eb-d17ca380da0a] raised unexpected: AttributeError("'NoneType' object has no attribute 'items'",)

File "/thewinegallery/src/thewinegalleryvenv/lib/python3.4/site-packages/easypost/__init__.py", line 810, in label
    self.refresh_from(response, api_key)
  File "/thewinegallery/src/thewinegalleryvenv/lib/python3.4/site-packages/easypost/__init__.py", line 452, in refresh_from
    for k, v in sorted(six.iteritems(values)):
  File "/thewinegallery/src/thewinegalleryvenv/lib/python3.4/site-packages/six.py", line 581, in iteritems
    return iter(d.items(**kw))
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by tpabla** [comment]
Based on the logs from our server your requests are coming through, however it appears that in your client code when requesting the label you are getting a nil response.  This may be due to a disconnect or timeout on your end (however the longest response time we've seen is 100ms, so a timeout is unlikely unless you have some custom logic).  This is for the account associated with you name.  

If you are still receiving this error please email support@easypost.com with a failing batch_id and when it occurred.  Also if you have any network timings that might suggest a timeout that would be helpful.  Feel free to mention me by name in the support ticket (Taran or tpabla) so I can help resolve this for you.

**Comment by jingta** [comment]
Closing, please reopen if the issue persists.
