### ISSUE TITLE
Is weight for parcel round up?

### ISSUE THREAD

**Issue by szewczykmira** [EasyPost/easypost-python#89]
Hi, 
I'm using this package to integrate project I'm working on with EasyPost, and during testing this integration I've encountered an issue:
``` python
from decimal import Decimal
full_weight = Decimal("20.7")

# here comes the code I'm using to create shipment
final_shipment = create_shipment(weight=full_weight, **args)
assert final_shipment.weight == full_weight
```
And I get fail on this line:
```
AssertionError: assert Decimal('21') == Decimal('20.7')
```

Does this mean that you are rounding up values? Or you don't accept weight?

**Comment by jontsai** [comment]
Hi @szewczykmira,

I'm not able to reproduce this issue because I don't know what `create_shipment` is doing -- that is not a part of the EasyPost Python library and possibly a wrapper function that is unique to your local codebase.

Do you have any additional information like: which carrier you were trying to create a shipment with?

In the basic/plain EasyPost Python library, this is the behavior:

```
In [1]: import easypost

In [2]: easypost.api_key = 'yourapikey'

In [3]: from decimal import Decimal

In [4]: full_weight = Decimal('20.7')

In [5]: parcel = easypost.Parcel.create(weight=full_weight)

In [6]: full_weight
Out[6]: Decimal('20.7')

In [7]: parcel.weight
Out[7]: 20.7

In [8]: type(parcel.weight)
Out[8]: float
```

As you can see from the above, once the object has been created in Python, the `type` turns into a `float`, but the value should still be the same.

The fact that you are seeing the weight as `Decimal('21')` after creating a shipment suggests to me that you might be using a carrier whose specific rating logic rounds up to the next ounce.

**Comment by szewczykmira** [comment]
Hey, I think I found an issue in my code in the most unexpected place and it doesn't have anything to do with you're project. And yet thank you, as your response lead me where to find a bug :)
