### ISSUE TITLE
Unable to cancel a pickup

### ISSUE THREAD

**Issue by catokx** [EasyPost/easypost-python#90]
Every time i try to cancel a pickup i receive this error message (it worked in past months)

Error in parsing request XML:Error: Element type \"MetaData\" must be declared.\n                    at line 11, column 13

**Comment by Justintime50** [comment]
Hey @catokx, can you provide some additional information? I just created and cancelled a pickup with the example `pickup_single_shipment.py` script found in this library and it worked just fine. Some code snippets or extra info would be helpful to know if this is a client library bug or if this is something in the way it's being implemented.

**Comment by Justintime50** [comment]
Hey @catokx, I'm closing this as it's been some time since you initially opened this issue without any follow up. Feel free to respond if you can provide additional details; otherwise this appears to be an intermittent issue or an issue with the code you used as the examples found in this repo worked correctly to create/cancel a pickup.
